name: Perch
options:
  bundleIdPrefix: com.tcballard
  deploymentTarget:
    macOS: "14.0"
settings:
  base:
    ARCHS: arm64
    CODE_SIGN_STYLE: Automatic
    CURRENT_PROJECT_VERSION: "8"
    DEVELOPMENT_TEAM: R8HXTBY3NM
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    MARKETING_VERSION: "0.1.0"
    SWIFT_VERSION: "5.0"
targets:
  Perch:
    type: application
    platform: macOS
    sources:
      - Sources/Perch
      - Sources/Shared
    dependencies:
      - target: PerchWidget
        embed: true
    info:
      path: Sources/Perch/Info.plist
      properties:
        CFBundleDisplayName: Perch
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSApplicationCategoryType: public.app-category.developer-tools
        LSMinimumSystemVersion: "14.0"
        LSUIElement: true
        NSHumanReadableCopyright: Copyright © 2026 Tom Ballard. All rights reserved.
        CFBundleURLTypes:
          - CFBundleURLName: com.tcballard.perch.focus
            CFBundleURLSchemes:
              - perch
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: Sources/Perch/Perch.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.tcballard.perch
        PRODUCT_NAME: Perch
      configs:
        Release:
          CODE_SIGN_INJECT_BASE_ENTITLEMENTS: NO
          ENABLE_HARDENED_RUNTIME: YES
  PerchWidget:
    type: app-extension
    platform: macOS
    sources:
      - Sources/PerchWidget
      - Sources/Shared
    info:
      path: Sources/PerchWidget/Info.plist
      properties:
        CFBundleDisplayName: Perch
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: true
        CODE_SIGN_ENTITLEMENTS: Sources/PerchWidget/PerchWidget.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.tcballard.perch.widget
        PRODUCT_NAME: PerchWidget
        SKIP_INSTALL: true
      configs:
        Release:
          CODE_SIGN_INJECT_BASE_ENTITLEMENTS: NO
          ENABLE_HARDENED_RUNTIME: YES
  PerchTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - tests/PerchTests
    dependencies:
      - target: Perch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tcballard.perch.tests
schemes:
  Perch:
    build:
      targets:
        Perch: all
        PerchTests: [test]
    test:
      targets:
        - PerchTests
